import { PrismaClient, Role, UserStatus, GameCategory, GameProviderType, Volatility, BonusType, BonusStatus } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const GAMES_DATA = [
  // SLOTS
  {
    slug: 'gates-of-olympus',
    title: 'Gates of Olympus',
    description: 'Tumble reels with Zeus multiplier orbs reaching up to 500x. Flashy Greek god theme.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.PRAGMATIC,
    rtp: 96.5,
    volatility: Volatility.VERY_HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 14230,
  },
  {
    slug: 'sweet-bonanza',
    title: 'Sweet Bonanza',
    description: 'Sugar-loaded cluster pays with candy bombs and massive multiplier tumble spins.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.PRAGMATIC,
    rtp: 96.48,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 12580,
  },
  {
    slug: 'fortune-tiger',
    title: 'Fortune Tiger',
    description: 'The golden golden tiger brings lucky respins and 10x multiplier win cards.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.PG_SOFT,
    rtp: 96.81,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 18940,
  },
  {
    slug: 'mahjong-ways-2',
    title: 'Mahjong Ways 2',
    description: 'Classic Chinese tile aesthetic with transforming gold symbols and multiplier cascades.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.PG_SOFT,
    rtp: 96.95,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 9450,
  },
  {
    slug: 'sugar-rush',
    title: 'Sugar Rush 1000',
    description: 'Sticky multiplier spots up to 1024x on explosive gummy cluster drops.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.PRAGMATIC,
    rtp: 96.53,
    volatility: Volatility.VERY_HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1575224300306-1b8da36134ec?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 8900,
  },
  {
    slug: 'lass-slot-777-deluxe',
    title: 'Lass Slot 777 Deluxe',
    description: 'Exclusive signature high-roller 777 slot with golden diamonds and mega jackpots.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.BIGSIX,
    rtp: 97.5,
    volatility: Volatility.VERY_HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 22400,
  },
  {
    slug: 'bigsix-vegas-gold',
    title: 'BigSix Vegas Gold',
    description: 'Vegas neon nightlife featuring stacked wilds and progressive wheel bonus.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.BIGSIX,
    rtp: 97.1,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: true,
    playCount: 6730,
  },
  {
    slug: 'super-ace',
    title: 'Super Ace',
    description: 'Poker playing card combo mechanic with elimination multipliers and golden card wilds.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.JILI,
    rtp: 97.0,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 11200,
  },
  {
    slug: 'boxing-king',
    title: 'Boxing King',
    description: 'Championship boxing match with combo hits, free games, and ring knockout wins.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.JILI,
    rtp: 97.13,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 5120,
  },
  {
    slug: 'roma-x',
    title: 'Roma X',
    description: 'Colosseum gladiators battle for glory with sword-strike cascades and bonus lions.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.JILI,
    rtp: 96.5,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 4300,
  },
  {
    slug: 'golden-empire',
    title: 'Golden Empire',
    description: 'Incan golden treasures with expanding framed wilds and unlimited multiplier free games.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.JILI,
    rtp: 97.06,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 3890,
  },
  {
    slug: 'starburst-xxxtreme',
    title: 'Starburst XXXtreme',
    description: 'Expanding Starburst wilds with random multipliers up to 450x and cosmic respins.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.NETENT,
    rtp: 96.26,
    volatility: Volatility.VERY_HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 7100,
  },
  {
    slug: 'gonzos-quest-megaways',
    title: 'Gonzo\'s Quest Megaways',
    description: 'The Spanish explorer journeys to El Dorado with avalanche multipliers and earthquake.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.NETENT,
    rtp: 96.0,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 6540,
  },
  {
    slug: 'buffalo-king-megaways',
    title: 'Buffalo King Megaways',
    description: 'Up to 200,704 ways to win across the American prairie with wild multipliers.',
    category: GameCategory.SLOTS,
    provider: GameProviderType.PRAGMATIC,
    rtp: 96.52,
    volatility: Volatility.VERY_HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef6?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 5890,
  },

  // CRASH GAMES
  {
    slug: 'aviator',
    title: 'Aviator',
    description: 'The world\'s #1 multiplayer social crash game. Cash out before the red lucky plane flies away!',
    category: GameCategory.CRASH,
    provider: GameProviderType.SPRIBE,
    rtp: 97.0,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f4?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f4?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 31200,
  },
  {
    slug: 'jetx',
    title: 'JetX',
    description: 'Blast off in a jet fighter. Parachute out before the jet explodes at altitude.',
    category: GameCategory.CRASH,
    provider: GameProviderType.BIGSIX,
    rtp: 97.0,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 14500,
  },
  {
    slug: 'space-xy',
    title: 'Space XY',
    description: 'Launch a rocket into deep space coordinates with real-time flight telemetry.',
    category: GameCategory.CRASH,
    provider: GameProviderType.BIGSIX,
    rtp: 97.0,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 8700,
  },
  {
    slug: 'spaceman',
    title: 'Spaceman',
    description: 'Pragmatic Play\'s cute astronaut flying into the cosmos with 50% cashout option.',
    category: GameCategory.CRASH,
    provider: GameProviderType.PRAGMATIC,
    rtp: 96.5,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 12100,
  },
  {
    slug: 'zeppelin',
    title: 'Zeppelin',
    description: 'Airship multiplier climbing into golden sunset skies with live player bets.',
    category: GameCategory.CRASH,
    provider: GameProviderType.SPRIBE,
    rtp: 96.4,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 4200,
  },

  // FISH GAMES
  {
    slug: 'ocean-king-3-plus',
    title: 'Ocean King 3 Plus',
    description: 'High-power underwater arcade cannon shooting. Hunt Golden Dragons and Thunder Crabs.',
    category: GameCategory.FISH,
    provider: GameProviderType.JILI,
    rtp: 97.2,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 19800,
  },
  {
    slug: 'cai-shen-fishing',
    title: 'Cai Shen Fishing',
    description: 'The God of Wealth brings prosperity bombs and golden toad jackpots.',
    category: GameCategory.FISH,
    provider: GameProviderType.JILI,
    rtp: 97.0,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 13400,
  },
  {
    slug: 'dragon-fortune-fishing',
    title: 'Dragon Fortune Fishing',
    description: 'Legendary dragon pearl cannons and chain-reaction lightning strikes.',
    category: GameCategory.FISH,
    provider: GameProviderType.JILI,
    rtp: 96.8,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 7600,
  },
  {
    slug: 'mega-fishing',
    title: 'Mega Fishing',
    description: 'Target boss sea monsters with laser torpedoes and awake the Mermaid treasure.',
    category: GameCategory.FISH,
    provider: GameProviderType.JILI,
    rtp: 97.0,
    volatility: Volatility.MEDIUM,
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 6200,
  },

  // LIVE CASINO
  {
    slug: 'mega-roulette',
    title: 'Mega Roulette Live',
    description: 'Live European roulette with up to 500x Mega Lucky Multipliers on straight-up bets.',
    category: GameCategory.LIVE,
    provider: GameProviderType.PRAGMATIC,
    rtp: 97.3,
    volatility: Volatility.LOW,
    thumbnail: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 15400,
  },
  {
    slug: 'lightning-blackjack',
    title: 'Lightning Blackjack Live',
    description: 'Score winning hands with guaranteed 2x to 25x lightning multiplier cards.',
    category: GameCategory.LIVE,
    provider: GameProviderType.EVOLUTION,
    rtp: 99.56,
    volatility: Volatility.LOW,
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 11800,
  },
  {
    slug: 'speed-baccarat-a',
    title: 'Speed Baccarat A',
    description: 'Fast-paced authentic dealer cards dealt face up in under 27 seconds.',
    category: GameCategory.LIVE,
    provider: GameProviderType.EVOLUTION,
    rtp: 98.94,
    volatility: Volatility.LOW,
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 8900,
  },
  {
    slug: 'crazy-time',
    title: 'Crazy Time Game Show',
    description: 'All-action wheel game show with Cash Hunt, Pachinko, Coin Flip, and Crazy Time bonus world.',
    category: GameCategory.LIVE,
    provider: GameProviderType.EVOLUTION,
    rtp: 96.08,
    volatility: Volatility.HIGH,
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 28400,
  },
];

async function main() {
  console.log('🌱 Starting database seeding for Lass777 Casino...');

  // 1. Create Admin User
  const adminPasswordHash = await bcrypt.hash('AdminPass777!', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@9casino.com' },
    update: {},
    create: {
      email: 'admin@9casino.com',
      username: '9casino_admin',
      role: Role.ADMIN,
      vipLevel: 5,
      status: UserStatus.ACTIVE,
      passwordHash: adminPasswordHash,
      wallet: {
        create: {
          realBalance: 50000.0,
          bonusBalance: 5000.0,
          currency: 'USD',
        },
      },
    },
    include: { wallet: true },
  });
  console.log(`✅ 9casino Admin user seeded: ${admin.email}`);

  // 1b. Legacy admin alias
  await prisma.user.upsert({
    where: { email: 'admin@lass777.com' },
    update: {},
    create: {
      email: 'admin@lass777.com',
      username: 'lass_admin',
      role: Role.ADMIN,
      vipLevel: 5,
      status: UserStatus.ACTIVE,
      passwordHash: adminPasswordHash,
      wallet: {
        create: {
          realBalance: 50000.0,
          bonusBalance: 5000.0,
          currency: 'USD',
        },
      },
    },
  }).catch(() => {});

  // 2. Create Demo User
  const demoPasswordHash = await bcrypt.hash('DemoPass777!', 10);
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@9casino.com' },
    update: {},
    create: {
      email: 'demo@9casino.com',
      username: 'lucky_player',
      phone: '+15557770199',
      role: Role.USER,
      vipLevel: 2,
      status: UserStatus.ACTIVE,
      passwordHash: demoPasswordHash,
      wallet: {
        create: {
          realBalance: 2500.0,
          bonusBalance: 500.0,
          currency: 'USD',
        },
      },
      bonuses: {
        create: {
          code: 'WELCOME200',
          type: BonusType.WELCOME_BONUS,
          amount: 500.0,
          wageringRequired: 15000.0,
          wageringProgress: 3500.0,
          status: BonusStatus.ACTIVE,
          expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        },
      },
    },
    include: { wallet: true },
  });
  console.log(`✅ 9casino Demo user seeded: ${demoUser.email}`);

  // 2b. Legacy demo alias
  await prisma.user.upsert({
    where: { email: 'demo@lass777.com' },
    update: {},
    create: {
      email: 'demo@lass777.com',
      username: 'lass_player',
      role: Role.USER,
      vipLevel: 2,
      status: UserStatus.ACTIVE,
      passwordHash: demoPasswordHash,
      wallet: {
        create: {
          realBalance: 2500.0,
          bonusBalance: 500.0,
          currency: 'USD',
        },
      },
    },
  }).catch(() => {});

  // 3. Seed initial transactions for demo user
  if (demoUser.wallet) {
    await prisma.transaction.createMany({
      data: [
        {
          walletId: demoUser.wallet.id,
          userId: demoUser.id,
          type: 'DEPOSIT' as any,
          amount: 2000.0,
          currency: 'USD',
          status: 'COMPLETED' as any,
          paymentMethod: 'USDT_TRC20',
          txHash: '0x8f3c7a9b1e4d56781234abcd5678ef01',
          createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        },
        {
          walletId: demoUser.wallet.id,
          userId: demoUser.id,
          type: 'BONUS' as any,
          amount: 500.0,
          currency: 'USD',
          status: 'COMPLETED' as any,
          paymentMethod: 'PROMO_WELCOME200',
          createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        },
        {
          walletId: demoUser.wallet.id,
          userId: demoUser.id,
          type: 'BET' as any,
          amount: 50.0,
          currency: 'USD',
          status: 'COMPLETED' as any,
          providerRef: 'gates-of-olympus',
          createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        },
        {
          walletId: demoUser.wallet.id,
          userId: demoUser.id,
          type: 'WIN' as any,
          amount: 550.0,
          currency: 'USD',
          status: 'COMPLETED' as any,
          providerRef: 'gates-of-olympus',
          createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        },
      ],
      skipDuplicates: true,
    });
  }

  // 4. Seed all 27 Games
  let gamesCreated = 0;
  for (const gameData of GAMES_DATA) {
    await prisma.game.upsert({
      where: { slug: gameData.slug },
      update: gameData,
      create: gameData,
    });
    gamesCreated++;
  }
  console.log(`✅ ${gamesCreated} games successfully seeded across Slots, Crash, Fish, and Live Casino.`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
