import { Game } from '@/types';

export const CATEGORIES = [
  { id: 'ALL', label: 'All Games', icon: 'Flame' },
  { id: 'SLOTS', label: 'Slots', icon: 'Coins' },
  { id: 'CRASH', label: 'Crash Games', icon: 'Rocket' },
  { id: 'FISH', label: 'Fish Arcade', icon: 'Fish' },
  { id: 'LIVE', label: 'Live Casino', icon: 'Tv' },
];

export const PROVIDERS = [
  { id: 'ALL', label: 'All Providers' },
  { id: 'PG_SOFT', label: 'PG Soft' },
  { id: 'PRAGMATIC', label: 'Pragmatic Play' },
  { id: 'JILI', label: 'JILI Games' },
  { id: 'SPRIBE', label: 'Spribe' },
  { id: 'BIGSIX', label: 'BigSix / Lass' },
  { id: 'EVOLUTION', label: 'Evolution Gaming' },
  { id: 'NETENT', label: 'NetEnt' },
];

export const VIP_TIERS = [
  { level: 1, name: 'Bronze High-Roller', cashback: '5%', perks: '$20 Free Play on Signup' },
  { level: 2, name: 'Silver VIP', cashback: '8%', perks: 'Weekly Reload + 24/7 VIP Host' },
  { level: 3, name: 'Gold Club', cashback: '12%', perks: 'Instant Payouts + Higher Limits' },
  { level: 4, name: 'Platinum Royale', cashback: '15%', perks: 'Exclusive Slots + Luxury Gifts' },
  { level: 5, name: 'Diamond Lass777', cashback: '20%', perks: 'Unlimited Limits + VIP Concierge' },
];

export const INITIAL_GAMES: Game[] = [
  {
    id: 'g-mafia-777',
    slug: 'mafia-syndicate-777',
    title: 'Mafia Syndicate 777',
    description: 'Underworld 1930s 5-reel mafia slot. Authoritative RNG with Wild Skulls, Bank Scatters, and 20 paylines.',
    category: 'SLOTS',
    provider: 'BIGSIX',
    rtp: 96.5,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 29800,
    active: true,
  },
  {
    id: 'g-mines-original',
    slug: 'mines',
    title: 'Mines Originals',
    description: 'Classic 5x5 minefield original. Uncover glowing emerald gems, dodge explosive bombs, and cash out at high multipliers.',
    category: 'TABLE',
    provider: 'BIGSIX',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 34500,
    active: true,
  },
  {
    id: 'g1',
    slug: 'gates-of-olympus',
    title: 'Gates of Olympus',
    description: 'Tumble reels with Zeus multiplier orbs reaching up to 500x. Flashy Greek god theme.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.5,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 14230,
    active: true,
  },
  {
    id: 'g2',
    slug: 'sweet-bonanza',
    title: 'Sweet Bonanza',
    description: 'Sugar-loaded cluster pays with candy bombs and massive multiplier tumble spins.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.48,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 12580,
    active: true,
  },
  {
    id: 'g3',
    slug: 'fortune-tiger',
    title: 'Fortune Tiger',
    description: 'The golden golden tiger brings lucky respins and 10x multiplier win cards.',
    category: 'SLOTS',
    provider: 'PG_SOFT',
    rtp: 96.81,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 18940,
    active: true,
  },
  {
    id: 'g4',
    slug: 'lass-slot-777-deluxe',
    title: 'Lass Slot 777 Deluxe',
    description: 'Exclusive signature high-roller 777 slot with golden diamonds and mega jackpots.',
    category: 'SLOTS',
    provider: 'BIGSIX',
    rtp: 97.5,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 22400,
    active: true,
  },
  {
    id: 'g5',
    slug: 'aviator',
    title: 'Aviator',
    description: "The world's #1 multiplayer social crash game. Cash out before the red lucky plane flies away!",
    category: 'CRASH',
    provider: 'SPRIBE',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f4?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f4?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 31200,
    active: true,
  },
  {
    id: 'g6',
    slug: 'jetx',
    title: 'JetX',
    description: 'Blast off in a jet fighter. Parachute out before the jet explodes at altitude.',
    category: 'CRASH',
    provider: 'BIGSIX',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 14500,
    active: true,
  },
  {
    id: 'g7',
    slug: 'ocean-king-3-plus',
    title: 'Ocean King 3 Plus',
    description: 'High-power underwater arcade cannon shooting. Hunt Golden Dragons and Thunder Crabs.',
    category: 'FISH',
    provider: 'JILI',
    rtp: 97.2,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 19800,
    active: true,
  },
  {
    id: 'g8',
    slug: 'cai-shen-fishing',
    title: 'Cai Shen Fishing',
    description: 'The God of Wealth brings prosperity bombs and golden toad jackpots.',
    category: 'FISH',
    provider: 'JILI',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 13400,
    active: true,
  },
  {
    id: 'g9',
    slug: 'mega-roulette',
    title: 'Mega Roulette Live',
    description: 'Live European roulette with up to 500x Mega Lucky Multipliers on straight-up bets.',
    category: 'LIVE',
    provider: 'PRAGMATIC',
    rtp: 97.3,
    volatility: 'LOW',
    thumbnail: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 15400,
    active: true,
  },
  {
    id: 'g10',
    slug: 'crazy-time',
    title: 'Crazy Time Game Show',
    description: 'All-action wheel game show with Cash Hunt, Pachinko, Coin Flip, and Crazy Time bonus world.',
    category: 'LIVE',
    provider: 'EVOLUTION',
    rtp: 96.08,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 28400,
    active: true,
  },
  {
    id: 'g11',
    slug: 'mahjong-ways-2',
    title: 'Mahjong Ways 2',
    description: 'Classic Chinese tile aesthetic with transforming gold symbols and multiplier cascades.',
    category: 'SLOTS',
    provider: 'PG_SOFT',
    rtp: 96.95,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 9450,
    active: true,
  },
  {
    id: 'g12',
    slug: 'super-ace',
    title: 'Super Ace',
    description: 'Poker playing card combo mechanic with elimination multipliers and golden card wilds.',
    category: 'SLOTS',
    provider: 'JILI',
    rtp: 97.0,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 11200,
    active: true,
  },
];
