import { Game } from '@/types';

export const CATEGORIES = [
  { id: 'ALL', label: 'All Games', icon: 'Flame' },
  { id: 'ORIGINALS', label: '9Casino Originals', icon: 'Zap' },
  { id: 'SLOTS', label: 'Slots', icon: 'Coins' },
  { id: 'LIVE', label: 'Live Casino', icon: 'Tv' },
  { id: 'CRASH', label: 'Crash Games', icon: 'Rocket' },
  { id: 'FISH', label: 'Arcade & Fish', icon: 'Fish' },
];

export const PROVIDERS = [
  { id: 'ALL', label: 'All Providers' },
  { id: 'BIGSIX', label: '9Casino Originals' },
  { id: 'PRAGMATIC', label: 'Pragmatic Play' },
  { id: 'NETENT', label: 'Hacksaw & NetEnt' },
  { id: 'EVOLUTION', label: 'Evolution Live' },
  { id: 'PG_SOFT', label: 'PG Soft' },
  { id: 'SPRIBE', label: 'Spribe' },
  { id: 'JILI', label: 'JILI Games' },
];

export const VIP_TIERS = [
  { level: 1, name: 'Bronze Explorer', cashback: '5%', perks: '$20 Free Play + 5% Instant Rakeback', wager: '$0 - $10k' },
  { level: 2, name: 'Silver High-Roller', cashback: '8%', perks: 'Weekly Reload + Dedicated VIP Host', wager: '$10k - $50k' },
  { level: 3, name: 'Gold Club', cashback: '12%', perks: 'Instant Payouts + Higher Limits + Monthly Bonus', wager: '$50k - $250k' },
  { level: 4, name: 'Platinum Elite', cashback: '15%', perks: 'Exclusive Slots + Luxury Gifts + Zero Fees', wager: '$250k - $1M' },
  { level: 5, name: 'Diamond 9Casino', cashback: '20%', perks: 'Unlimited Limits + VIP Concierge + Custom Rakeback', wager: '$1M+' },
];

export const INITIAL_GAMES: Game[] = [
  // ================= 9CASINO ORIGINALS (Stake & Rainbet inspired) =================
  {
    id: 'g-plinko',
    slug: 'plinko',
    title: 'Plinko Originals',
    description: 'The iconic pegboard pyramid. Drop balls from the top and watch them bounce into high-multiplier buckets up to 1,000x.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 54200,
    active: true,
  },
  {
    id: 'g-mines-original',
    slug: 'mines',
    title: 'Mines Originals',
    description: 'Classic 5x5 minefield original. Uncover glowing emerald gems, dodge explosive bombs, and cash out at high multipliers.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 48900,
    active: true,
  },
  {
    id: 'g-crash-original',
    slug: 'crash',
    title: 'Crash Originals',
    description: 'High-octane multiplier rocket launch. Watch the curve rise into orbit and cash out before the inevitable crash!',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 62400,
    active: true,
  },
  {
    id: 'g-limbo',
    slug: 'limbo',
    title: 'Limbo Rocket',
    description: 'Set your target multiplier up to 1,000,000x! Blast off and win if the lucky rocket flies above your target.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 31200,
    active: true,
  },
  {
    id: 'g-dice',
    slug: 'dice',
    title: 'Crypto Dice',
    description: 'The foundation of crypto gambling. Adjust your win chance slider from 0.01% to 98% with instantaneous provably fair rolls.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'LOW',
    thumbnail: 'https://images.unsplash.com/photo-1570303345338-e1f0eddf4946?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 27800,
    active: true,
  },
  {
    id: 'g-wheel',
    slug: 'wheel',
    title: 'Lucky Wheel 9',
    description: 'Multi-risk prize wheel. Select low, medium, or high risk segments for lightning multiplier rewards.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 19400,
    active: true,
  },
  {
    id: 'g-keno',
    slug: 'keno',
    title: 'Neon Keno',
    description: 'Pick up to 10 lucky neon numbers on the digital grid. Match the drawn numbers to score huge payouts.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 15300,
    active: true,
  },
  {
    id: 'g-hilo',
    slug: 'hilo',
    title: 'HiLo Master',
    description: 'Guess if the next card will be Higher, Lower, or Same. Chain multiple correct guesses for compounding multipliers.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 18200,
    active: true,
  },
  {
    id: 'g-dragon-tower',
    slug: 'dragon-tower',
    title: 'Dragon Tower',
    description: 'Climb the ancient castle tower floor by floor. Choose the right stone to dodge dragon flames and reach the gold.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 99.0,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 22100,
    active: true,
  },
  {
    id: 'g-cases',
    slug: 'cases',
    title: 'Crypto Cases',
    description: 'Rainbet-style mystery loot cases. Unbox rare crypto prizes, jackpot tickets, and massive multipliers.',
    category: 'ORIGINALS',
    provider: 'BIGSIX',
    rtp: 98.5,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 34100,
    active: true,
  },
  {
    id: 'g-mafia-777',
    slug: 'mafia-syndicate-777',
    title: '9Casino 777 Syndicate',
    description: 'Underworld 1930s 5-reel mafia slot. Authoritative RNG with Wild Skulls, Bank Scatters, and 20 paylines.',
    category: 'SLOTS',
    provider: 'BIGSIX',
    rtp: 97.2,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 29800,
    active: true,
  },

  // ================= PRAGMATIC PLAY BLOCKBUSTERS =================
  {
    id: 'g1',
    slug: 'gates-of-olympus',
    title: 'Gates of Olympus 1000',
    description: 'Zeus summons electric tumble multiplier orbs reaching up to 1000x! Greek mythology with free spins retriggers.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.5,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 78500,
    active: true,
  },
  {
    id: 'g2',
    slug: 'sweet-bonanza',
    title: 'Sweet Bonanza 1000',
    description: 'Sugar-loaded cluster pays with rainbow candy bombs up to 1000x and unlimited multiplier tumble spins.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.53,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 71200,
    active: true,
  },
  {
    id: 'g-sugar-rush',
    slug: 'sugar-rush',
    title: 'Sugar Rush 1000',
    description: 'Explosive gummy cluster drops with persistent multiplier spots doubling up to 1024x on every tumble.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.53,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1575224300306-1b8da36134ec?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 52400,
    active: true,
  },
  {
    id: 'g-big-bass',
    slug: 'big-bass-splash',
    title: 'Big Bass Splash',
    description: 'Cast your line with the bearded fisherman! Hook monster bass with cash tags, bazookas, dynamite, and free spins.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.71,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 46800,
    active: true,
  },
  {
    id: 'g-dog-house',
    slug: 'the-dog-house-megaways',
    title: 'The Dog House Megaways',
    description: 'Up to 117,649 ways to win with rottweilers, pugs, and sticky multiplier dog house wilds up to 3x.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.55,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: true,
    playCount: 38900,
    active: true,
  },
  {
    id: 'g-zeus-vs-hades',
    slug: 'zeus-vs-hades',
    title: 'Zeus vs Hades: Gods of War',
    description: 'Choose your volatility mode: Olympus vs Hades. Expanding VS wilds fight with random multipliers up to 100x.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.07,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 33400,
    active: true,
  },
  {
    id: 'g-starlight-princess',
    slug: 'starlight-princess',
    title: 'Starlight Princess 1000',
    description: 'Anime castle in the clouds! Floating multiplier hearts boost tumble cascades up to 1000x.',
    category: 'SLOTS',
    provider: 'PRAGMATIC',
    rtp: 96.5,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 29500,
    active: true,
  },

  // ================= HACKSAW GAMING FAVORITES =================
  {
    id: 'g-wanted',
    slug: 'wanted-dead-or-a-wild',
    title: 'Wanted Dead or a Wild',
    description: 'Gritty sepia Western showdown. The Great Train Robbery, Duel at Dawn with VS multiplier wilds up to 100x, and Dead Mans Hand.',
    category: 'SLOTS',
    provider: 'NETENT',
    rtp: 96.38,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 65100,
    active: true,
  },
  {
    id: 'g-rip-city',
    slug: 'rip-city',
    title: 'RIP City',
    description: 'Monochrome alley street art with Roosh the Cat and Maxx the Mouse. Expanding Wild Cat jaws drop multipliers.',
    category: 'SLOTS',
    provider: 'NETENT',
    rtp: 96.22,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 41200,
    active: true,
  },
  {
    id: 'g-dork-unit',
    slug: 'dork-unit',
    title: 'Dork Unit',
    description: 'Hilarious cartoon clown show with mystery Gift Box wilds revealing multipliers up to 200x and Dork Spins bonus.',
    category: 'SLOTS',
    provider: 'NETENT',
    rtp: 96.24,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 26800,
    active: true,
  },
  {
    id: 'g-chaos-crew',
    slug: 'chaos-crew-2',
    title: 'Chaos Crew 2',
    description: 'Cranky Cat and Sketchy skull bring an anti-establishment graffiti vibe with multiplying sticky bonus grids.',
    category: 'SLOTS',
    provider: 'NETENT',
    rtp: 96.27,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 22700,
    active: true,
  },

  // ================= LIVE CASINO & GAME SHOWS =================
  {
    id: 'g10',
    slug: 'crazy-time',
    title: 'Crazy Time Game Show',
    description: 'The worlds #1 live wheel game show! 4 massive bonus rounds: Cash Hunt, Pachinko, Coin Flip, and the Crazy Time red door.',
    category: 'LIVE',
    provider: 'EVOLUTION',
    rtp: 96.08,
    volatility: 'VERY_HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 84300,
    active: true,
  },
  {
    id: 'g-lightning-roulette',
    slug: 'lightning-roulette',
    title: 'Lightning Roulette Live',
    description: 'High-voltage live roulette! In every round, 1 to 5 lucky numbers are struck by lightning with 50x to 500x multipliers.',
    category: 'LIVE',
    provider: 'EVOLUTION',
    rtp: 97.3,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 58900,
    active: true,
  },
  {
    id: 'g-monopoly-live',
    slug: 'monopoly-live',
    title: 'Monopoly Live',
    description: 'Roll the dice and join Mr. Monopoly in 3D augmented reality! Walk Mayfair, collect rent, and multiply your payout.',
    category: 'LIVE',
    provider: 'EVOLUTION',
    rtp: 96.23,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 44200,
    active: true,
  },
  {
    id: 'g-blackjack-vip',
    slug: 'blackjack-vip',
    title: 'Blackjack VIP Salon Privé',
    description: 'Sleek emerald velvet table with high-roller limits, dedicated private croupier, and perfect pairs side bets.',
    category: 'LIVE',
    provider: 'EVOLUTION',
    rtp: 99.28,
    volatility: 'LOW',
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: true,
    playCount: 31700,
    active: true,
  },
  {
    id: 'g-candyland',
    slug: 'sweet-bonanza-candyland',
    title: 'Sweet Bonanza CandyLand Live',
    description: 'The candy slot universe brought to life on a giant 54-segment live wheel with Sweet Spins and Candy Drop bonuses.',
    category: 'LIVE',
    provider: 'PRAGMATIC',
    rtp: 96.48,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 28400,
    active: true,
  },

  // ================= PG SOFT & ASIAN FAVORITES =================
  {
    id: 'g3',
    slug: 'fortune-tiger',
    title: 'Fortune Tiger',
    description: 'The golden tiger brings lucky respins and full-screen 10x multiplier win cards. Very popular fast-paced mobile slot.',
    category: 'SLOTS',
    provider: 'PG_SOFT',
    rtp: 96.81,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 49800,
    active: true,
  },
  {
    id: 'g11',
    slug: 'mahjong-ways-2',
    title: 'Mahjong Ways 2',
    description: 'Classic Chinese tile aesthetic with transforming gold symbols and multiplier cascades reaching up to 10x.',
    category: 'SLOTS',
    provider: 'PG_SOFT',
    rtp: 96.95,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: false,
    playCount: 39400,
    active: true,
  },
  {
    id: 'g-fortune-ox',
    slug: 'fortune-ox',
    title: 'Fortune Ox',
    description: 'Year of the Ox brings golden horns and guaranteed winning respins with 10x multiplier boost.',
    category: 'SLOTS',
    provider: 'PG_SOFT',
    rtp: 96.75,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 24100,
    active: true,
  },
  {
    id: 'g12',
    slug: 'super-ace',
    title: 'Super Ace',
    description: 'Card suit combos with elimination cascades, transforming golden cards, and up to 5x multiplier combos.',
    category: 'SLOTS',
    provider: 'JILI',
    rtp: 97.0,
    volatility: 'HIGH',
    thumbnail: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 22600,
    active: true,
  },
  {
    id: 'g-boxing-king',
    slug: 'boxing-king',
    title: 'Boxing King',
    description: 'Championship boxing match with combo hits, free games, and ring knockout wins.',
    category: 'SLOTS',
    provider: 'JILI',
    rtp: 97.13,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 17400,
    active: true,
  },

  // ================= CRASH & ARCADE FISH =================
  {
    id: 'g5',
    slug: 'aviator',
    title: 'Aviator',
    description: 'The worlds #1 multiplayer social crash game. Cash out before the red lucky propeller plane flies away!',
    category: 'CRASH',
    provider: 'SPRIBE',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f4?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 68400,
    active: true,
  },
  {
    id: 'g6',
    slug: 'jetx',
    title: 'JetX',
    description: 'Blast off in a supersonic jet fighter. Parachute out before the jet explodes in mid-air.',
    category: 'CRASH',
    provider: 'BIGSIX',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 25100,
    active: true,
  },
  {
    id: 'g7',
    slug: 'ocean-king-3-plus',
    title: 'Ocean King 3 Plus',
    description: 'High-power underwater arcade cannon shooting. Hunt Golden Dragons and Thunder Crabs for big bounties.',
    category: 'FISH',
    provider: 'JILI',
    rtp: 97.2,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=700&q=80',
    isHot: true,
    isFeatured: true,
    playCount: 31200,
    active: true,
  },
  {
    id: 'g8',
    slug: 'cai-shen-fishing',
    title: 'Cai Shen Fishing',
    description: 'The God of Wealth brings prosperity bombs and golden toad jackpots in this multiplayer fish shooting arena.',
    category: 'FISH',
    provider: 'JILI',
    rtp: 97.0,
    volatility: 'MEDIUM',
    thumbnail: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&w=700&q=80',
    isHot: false,
    isFeatured: false,
    playCount: 21800,
    active: true,
  },
];
